service:
  name: test-serverless-typescript-circleci

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

# exclude code coverage files from the zip package
package:
  exclude:
  - coverage/**

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
